### ISSUE TITLE
Module not found: Can't resolve 'index.css'

### ISSUE THREAD

**Issue by codemeasandwich** [500tech/middleware-lecture#1]
Thanks for sharing your code.

I ran `yarn start` but get 

```
Failed to compile.

./src/index.js
Module not found: Can't resolve 'index.css' in '/home/brian/www/middleware-lecture/src'
```

and a message of _"This error occurred during the build time and cannot be dismissed."_

Any thoughts?
Thanks

**Comment by borisd** [comment]
What env are you running on?

The trick here is the absolute paths (instead of import "../../" stuff. There is an ".env" file in the root that defines ```NODE_PATH=src/```.  

Are you on Windows?
